import { access, copyFile, mkdir } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function pathFromRoot(...parts) {
  return resolve(repoRoot, ...parts);
}

async function exists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch (_) {
    return false;
  }
}

async function bundleManggo() {
  await build({
    entryPoints: [pathFromRoot("src", "manggo", "entry.js")],
    outfile: pathFromRoot("main.js"),
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2020",
    legalComments: "none",
    banner: { js: "// Generated by npm run build. Do not edit directly." },
  });
}

async function bundleBobCore(platform) {
  const libDirectory = pathFromRoot("platforms", platform, "lib");
  await mkdir(libDirectory, { recursive: true });
  await build({
    entryPoints: [pathFromRoot("src", "core", "index.js")],
    outfile: resolve(libDirectory, "core.cjs"),
    bundle: true,
    format: "cjs",
    platform: "neutral",
    target: "es2017",
    legalComments: "none",
    banner: { js: "// Generated from src/core by npm run build. Do not edit directly." },
  });
  // Bob's documentation demonstrates require() with .js paths.  Keep the
  // .cjs file for Node-side tooling and provide an identical Bob-facing path.
  await copyFile(resolve(libDirectory, "core.cjs"), resolve(libDirectory, "core.js"));
}

// The small, checked-in bundle keeps Bob's source/development entry runnable
// without the optional full Core. All maintained logic stays in src/core.
export async function bundleBobStreaming(write = true) {
  return build({
    stdin: {
      contents: 'export { contentText, eventData, parseSseEvent } from "./responses.js";\n'
        + 'export { createStreamBatcher } from "./streaming.js";',
      resolveDir: pathFromRoot("src", "core"),
      sourcefile: "bob-streaming-entry.js",
    },
    outfile: pathFromRoot("src", "bob", "common", "streaming-core.js"),
    bundle: true,
    format: "cjs",
    platform: "neutral",
    target: "es2017",
    legalComments: "none",
    banner: { js: "// Generated from src/core by npm run build. Do not edit directly." },
    write,
  });
}

async function copyBobOcrRuntime() {
  const sourceDirectory = pathFromRoot("src", "bob", "ocr");
  const destinationDirectory = pathFromRoot("platforms", "bob-ocr", "lib");
  const names = ["image.cjs", "languages.cjs", "plugin.cjs"];
  if (!(await exists(sourceDirectory))) return;
  await mkdir(destinationDirectory, { recursive: true });
  await Promise.all(names.map(async (name) => {
    const source = resolve(sourceDirectory, name);
    if (!(await exists(source))) return;
    await copyFile(source, resolve(destinationDirectory, name));
    await copyFile(source, resolve(destinationDirectory, name.replace(/\.cjs$/, ".js")));
  }));
}

async function copyBobTranslateRuntime() {
  const mappings = [
    ["common/options.js", "common/options.js"],
    ["common/languages.js", "common/languages.js"],
    ["common/sse.js", "common/sse.js"],
    ["common/streaming-core.js", "common/streaming-core.js"],
    ["common/transport.js", "common/transport.js"],
    ["translate/main.js", "translate/main.js"],
  ];
  const sourceDirectory = pathFromRoot("src", "bob");
  const destinationDirectory = pathFromRoot("platforms", "bob-translate", "lib");
  for (const [sourceName, destinationName] of mappings) {
    const destination = resolve(destinationDirectory, destinationName);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(resolve(sourceDirectory, sourceName), destination);
  }
}

async function copyBobIcons() {
  const icon = pathFromRoot("icon.png");
  await Promise.all(["bob-translate", "bob-ocr"].map(async (platform) => {
    const platformDirectory = pathFromRoot("platforms", platform);
    if (await exists(platformDirectory)) await copyFile(icon, resolve(platformDirectory, "icon.png"));
  }));
}

async function buildBobArtifacts() {
  const ocrPlatform = pathFromRoot("platforms", "bob-ocr");
  if (await exists(ocrPlatform)) {
    await bundleBobCore("bob-ocr");
    await copyBobOcrRuntime();
  }

  // The translate platform may be added independently.  It receives the same
  // pure core bundle plus JavaScriptCore-compatible adapter files.
  const translatePlatform = pathFromRoot("platforms", "bob-translate");
  if (await exists(translatePlatform)) {
    await bundleBobStreaming();
    await bundleBobCore("bob-translate");
    await copyBobTranslateRuntime();
  }

  await copyBobIcons();
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await bundleManggo();
  await buildBobArtifacts();
}
